version: 2
updates:
  # NuGet config for 'SmallsOnline.PasswordExpirationNotifier.Lib'
  - package-ecosystem: "nuget"
    directory: "/src/Lib"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"
  
  # NuGet config for 'SmallsOnline.PasswordExpirationNotifier.FunctionApp'
  - package-ecosystem: "nuget"
    directory: "/src/FunctionApp"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"
  
  # NuGet config for 'SmallsOnline.PasswordExpirationNotifier.AdminConsole'
  - package-ecosystem: "nuget"
    directory: "/src/AdminConsole"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"
  
  # NPM config for 'SmallsOnline.PasswordExpirationNotifier.AdminConsole'
  - package-ecosystem: "npm"
    directory: "/src/AdminConsole"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"
  
  # GitHub Actions config for the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"