# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: AdminConsole Web App / Create container image
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  create-container-image:
    name: Create container image
    runs-on: ubuntu-latest

    env:
      EVENT_TYPE: ${{ github.event_name }}
      TAG_NAME: ${{ github.ref_name }}

    steps:
      - name: Generate image tag value
        shell: pwsh
        run: |
          "IMAGE_TAG=$($env:EVENT_TYPE -eq "push" ? $env:TAG_NAME : $([datetime]::Now.ToString("yyyyMMddTHHmmss")))" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.actor }}/SmallsOnline-PasswordExpirationNotifier-AdminConsole
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.admin-console
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "GITHUB_USER=${{ github.actor }}"
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
