# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build project
on:
  - push
  - pull_request
  - workflow_dispatch

permissions:
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        project: [
          "FunctionApp",
          "Lib",
          "AdminConsole"
        ]
    env:
      DOTNET_NOLOGO: true
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Setup GitHub Packages source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Build project
        shell: pwsh
        run: dotnet restore "./src/${{ matrix.project }}/" ; dotnet build "./src/${{ matrix.project }}/"
